language: bash

services:
  - docker

before_install:
  - docker pull asciishell/docker-latex
script:
  - docker run -u root --rm  -it -v $(pwd):/source asciishell/docker-latex bash ./build.sh

deploy:
  - provider: releases
    api_key: $TOKEN
    file: 
      - "Lab_02/main_02.pdf"
      - "Lab_03/main_03.pdf"
      - "Lab_04/main_04.pdf"
      - "Lab_05/main_05.pdf"
    skip_cleanup: true
    on:
      branch: master
